# Generated by Django 2.1.4 on 2018-12-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-pk']},
        ),
    ]
