# Generated by Django 2.1.4 on 2018-12-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
